version: "3.5"

networks:
    habnet:
        name: habnet
        driver: overlay
        attachable: true
        
configs:
    backup_config:
        file: ./volumerize/backup_config.json
    sftp_config:
        file: ./ssh/sshd_config
    sftp_users:
        file: ./ssh/sftp_users.conf
    sftp_key_ed:
        file: ./ssh/ssh_host_ed25519_key
    sftp_id_pub:
        file: ./ssh/id_rsa.pub
    sftp_id_key:
        file: ./ssh/id_rsa
    sftp_known_hosts:
        file: ./ssh/known_hosts
    traefik_config:
        file: ./traefik/traefik.toml
    traefik_users:
        file: ./traefik/traefik_users
    nodered_settings:
        file: ./nodered/nodered_settings.js
    nodered_package:
        file: ./nodered/nodered_package.json
    mosquitto_passwords:
        file: ./mosquitto/mosquitto_passwords
    mosquitto_settings:
        file: ./mosquitto/mosquitto.conf
    postgres_user:
        file: ./postgres/user
    postgres_passwd:
        file: ./postgres/passwd
    landing_logo:
        file: ./pb-framr/logo.svg
    landing_pages:
        file: ./pb-framr/pages.json
    filebrowser:
        file: ./filebrowser/filebrowser.json

volumes:
    openhab_addons:
    openhab_conf:
    openhab_userdata:
    nodered_data:
    mosquitto_data:
    influxdb_data:
    postgres_data:
    backup_data:
    backup_cache:

    
services:
    proxy:
        image: "traefik"
        command: --api --docker --docker.swarmMode --logLevel="DEBUG"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - "8080:8080"
            - "80:80"
        networks:
            - habnet
        configs:
            - source: traefik_config
              target: /etc/traefik/traefik.toml
            - source: traefik_users
              target: /etc/traefik/traefik_users
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager
    landing:
        image: doblix/pb-framr
        networks:
          - habnet
        configs:
          - source: landing_logo
            target: /usr/share/nginx/html/logo.svg
          - source: landing_pages
            target: /usr/share/nginx/html/pages.json
        deploy:
            labels:
              - traefik.docker.network=habnet
              - traefik.port=80
              - traefik.backend=landing
              - traefik.main.frontend.priority=2
              - traefik.main.frontend.redirect.regex=^(.*)/landing$$
              - traefik.main.frontend.redirect.replacement=$$1/landing/
              - traefik.main.frontend.rule=PathPrefix:/landing;ReplacePathRegex:^/landing/(.*)
                /$$1
            placement:
                constraints:
                    - node.role == manager
