################################################################
# Docker configuration backend
################################################################
debug = false

defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.http.auth.basic]
    usersFile = "/etc/traefik/traefik_users"
